In [1]:
import numpy as np

In [41]:
# create a 5 by 5 matrix containing ones
figure = np.ones((5,5), dtype = int)
figure

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
#create a 3 by 3 matrix containing zeros
zeros = np.zeros((3, 3), dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [43]:
# slice the figure matrix and replace with the zeros matrix
figure[1:4, 1:4] = zeros

In [44]:
figure

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [49]:
figure[2,2] = 9 # replace the value at 3rd element in the 3rd row with 9

In [50]:
figure

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])