In [1]:
import numpy as np

#### A NumPy program that creates a vector of length 5 filled with arbitrary integers from 0 to 10

In [3]:
arbitrary_vector = np.random.randint(0, 11, size=5)

print(arbitrary_vector)

[10 10  1  7  2]


#### A NumPy program that creates a vector with values ranging from 15 to 55 and prints all values except the first and last.

In [4]:
# creating a NumPy vector of values ranging from 15 to 55
vector = np.arange(15, 56)

# printing all values except the first and last
print(vector[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


#### A NumPy program to create a random array with 1000 elements and computes the average, variance, standard deviation of the array elements. 

In [9]:
# create a random NumPy array with 1000 elements
random_array = np.random.rand(1000)

# compute the average of the array elements
Average = np.average(random_array)

# compute the variance of the array elements
Variance = np.var(random_array)

# compute the standard deviation of the array elements
Std_dev = np.std(random_array)

print("The Average is " + str(Average))
print("The Variance is " + str(Variance))
print("The Standard deviation is " + str(Std_dev))

The Average is 0.5022444629429974
The Variance is 0.08475800003188763
The Standard deviation is 0.291132272398454


#### A NumPy program that calculates the cumulative sum of elements along a given axis, sum over rows for each of the 3 columns and sum over columns for each of the 2 rows of a given 3x3 array.

In [10]:
# create a 3x3 NumPy array
arr = np.array([[2, 5, 1], [5, 3, 2], [6, 1, 8]])

# calculate cumulative sum along axis 0 (columns)
cumulativeSum_axis0 = np.cumsum(arr, axis=0)

# calculate cumulative sum along axis 1 (rows)
cumulativeSum_axis1 = np.cumsum(arr, axis=1)

# calculate sum over rows for each of the 3 columns
sum_rows = np.sum(arr, axis=0)

# calculate sum over columns for each of the 2 rows
sum_cols = np.sum(arr, axis=1)

print("Original array:\n", arr)
print("Cumulative sum along axis 0:\n", cumulativeSum_axis0)
print("Cumulative sum along axis 1:\n", cumulativeSum_axis1)
print("Sum over rows for each of the 3 columns:\n", sum_rows)
print("Sum over columns for each of the 2 rows:\n", sum_cols)

Original array:
 [[2 5 1]
 [5 3 2]
 [6 1 8]]
Cumulative sum along axis 0:
 [[ 2  5  1]
 [ 7  8  3]
 [13  9 11]]
Cumulative sum along axis 1:
 [[ 2  7  8]
 [ 5  8 10]
 [ 6  7 15]]
Sum over rows for each of the 3 columns:
 [13  9 11]
Sum over columns for each of the 2 rows:
 [ 8 10 15]


#### A NumPy program to compute the multiplication of two given matrices.

In [11]:
# define two matrices
Matrix1 = np.array([[1, 0], [0, 1]])
Matrix2 = np.array([[1, 2], [3, 4]])

# compute the multiplication of the two matrices
result = Matrix1 @ Matrix2

print(result)

[[1 2]
 [3 4]]
